version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: mongo-konecta
    restart: always
    environment:
      MONGO_INITDB_DATABASE: konecta
    ports:
      - "27022:27017"
    volumes:
      - ~/konecta/mongo:/data/db
    networks:
      - konecta

  backend:
    build: ./backend
    ports:
      - 3022:3000
    depends_on:
      - mongo
    networks:
      - konecta
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - mongo
    networks:
      - konecta
networks:
  silvereconomy:
